### ISSUE TITLE
Wavelength of light

### ISSUE THREAD

**Issue by peterhcharlton** [microsoft/aurorabp-sample-data#13]
I wondered whether you could clarify what wavelength(s) of light was used to acquire the PPG signals in this dataset?

I've checked the [docs](https://github.com/microsoft/aurorabp-sample-data/blob/main/docs/README.md) and [study paper](https://doi.org/10.1109/JBHI.2022.3153259) and haven't found this information.

The datasheet for the PPG sensor (the [MAX30101 datasheet](https://www.analog.com/en/products/max30101.html)) seems to indicate that the sensor can record green, red and infrared signals, and I wondered which color light was used for the PPG signals in the dataset?

Many thanks.

**Comment by jeremiahwander** [comment]
@peterhcharlton - thank you for highlighting this issue. We've addressed this in the docs in PR #14. The Green LED was used for PPG data collection. Detailed operating characteristics for that LED can be pulled from the MAX30101 datasheet.

**Comment by peterhcharlton** [comment]
Excellent - that's very helpful. Thank you
